[package]
name = "SimpleKeyValue"
version = "0.1.0"
authors = ["eren <erenerisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.4"